ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/bst.cpp .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/bst.h .
ln -s /home/descent/git/jserv-course/stm32f4_prog/inc/core_cm4.h .
ln -s /home/descent/git/jserv-course/stm32f4_prog/inc/core_cm4_simd.h .
ln -s /home/descent/git/jserv-course/stm32f4_prog/inc/core_cmFunc.h .
ln -s /home/descent/git/jserv-course/stm32f4_prog/inc/core_cmInstr.h .
ln -s /home/descent/git/jserv-course/cm3_simple_os/crtbegin.cpp .
ln -s /home/descent/git/jserv-course/cm3_simple_os/crtbegin.h .
ln -s /home/descent/git/jserv-course/cm3_simple_os/eh.cpp .
ln -s /home/descent/git/jserv-course/cm3_simple_os/eh.h .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/gdeque.cpp .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/gdeque.h .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/k_stdio.cpp .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/k_stdio.h .
ln -s /home/descent/git/jserv-course/stm32f4_prog/stm32f4_simple_scheme/k_string.h .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/mem.cpp .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/mem.h .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/myiostream.cpp .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/myiostream.h .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/mylist.cpp .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/mylist.h .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/mymap.cpp .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/mymap.h .
ln -s /home/descent/git/jserv-course/stm32f4_prog/myjmp/my_setjmp.h .
ln -s /home/descent/git/jserv-course/stm32f4_prog/myjmp/my_setjmp.S .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/mystring.cpp .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/mystring.h .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/myvec.cpp .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/myvec.h .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/stm32f10x_conf.h .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/stm32f10x.h .
ln -s /home/descent/git/jserv-course/stm32f4_prog/inc/stm32f4xx_gpio.h .
ln -s /home/descent/git/jserv-course/stm32f4_prog/inc/stm32f4xx.h .
ln -s /home/descent/git/jserv-course/stm32f4_prog/inc/stm32f4xx_rcc.h .
ln -s /home/descent/git/jserv-course/stm32f4_prog/inc/stm32f4xx_usart.h .
ln -s /home/descent/git/jserv-course/cm3_simple_os/stm32.h .
ln -s /home/descent/git/jserv-course/stm32_p103_demos/demos/uart_echo/mymap/type.h .
